# Project meta
pluginVersion = 1.0.0
release = true
group = au.com.mineauz

mcVersion = 1.21.8
## Note: .github/workflows also needs adjusting!
javaVersion = 21

bstatsVersion = 3.1.0
paste-ggVersion = 2.0.0-SNAPSHOT
commons-lang3Version = 3.18.0
commons-textVersion = 1.13.1
commons-ioVersion = 2.20.0
sqlite-jdbcVersion = 3.50.2.0
mysql-connector-jVersion = 9.3.0
jetbrainsAnnotations = 26.0.2

vaultVersion =1.7.1
placeholderApiVersion = 2.11.6
worldeditVersionCompile = 7.4.0-SNAPSHOT
worldeditVersionRunTask = 7.4.0-SNAPSHOT

# Gradle configuration
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
