# Project meta
pluginVersion = 1.0.0
release = false
group = au.com.mineauz

mcVersion = 1.21.8
## Note: .github/workflows also needs adjusting!
javaVersion = 21

bstatsVersion = 3.1.0
pastefyVersion = 1.0.2-SNAPSHOT
commons-lang3Version = 3.18.0
commons-textVersion = 1.13.1
commons-ioVersion = 2.20.0
sqlite-jdbcVersion = 3.50.2.0
mysql-connector-jVersion = 9.3.0
jetbrainsAnnotations = 26.0.2

## Note: vault is split into api, for compiling against and the second one is the actual plugin to use in the run task.
### https://github.com/MilkBowl/Vault
vaultApiVersion = 1.7.1
### https://github.com/MilkBowl/VaultAPI
vaultVersionRunTask = 1.7.3
placeholderApiVersion = 2.11.6
## Note: the first is the maven api version, the second the wierd modrinth id
### this is the api to compile against
worldeditVersionCompile = 7.4.0-SNAPSHOT
### this is the ready to use .jar used in the run task
worldeditVersionRunTask = Jk1z2u7n

## Note: gradle plugins like userdev or run-paper can't get an entry here because of kotlin's limitations.

# Gradle configuration
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
