/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "MinigamesProject"
include(":Minigames")
include(":Minigames-Regions")
include(":minigames-distribution")
project(":Minigames-Regions").projectDir = file("Regions")
project(":minigames-distribution").projectDir = file("minigamesdistribution")
