/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.bstats.bstats.bukkit)
    api(libs.org.kitteh.paste.gg.api)
    api(libs.org.apache.commons.commons.lang3)
    api(libs.org.apache.commons.commons.text)
    api(libs.commons.io.commons.io)
    testImplementation(libs.com.github.seeseemelk.mockbukkit.v1.v20)
    testImplementation(libs.com.mysql.mysql.connector.j)
    compileOnly(libs.com.github.milkbowl.vaultapi)
    compileOnly(libs.org.xerial.sqlite.jdbc)
    compileOnly(libs.me.clip.placeholderapi)
    compileOnly(libs.com.sk89q.worldedit.worldedit.bukkit)
}

description = "Minigames"
